/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShoesIdRouteImport } from './routes/shoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesIdRoute = ShoesIdRouteImport.update({
  id: '/shoes/$id',
  path: '/shoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviews': typeof ReviewsRoute
  '/shop': typeof ShopRoute
  '/shoes/$id': typeof ShoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviews': typeof ReviewsRoute
  '/shop': typeof ShopRoute
  '/shoes/$id': typeof ShoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reviews': typeof ReviewsRoute
  '/shop': typeof ShopRoute
  '/shoes/$id': typeof ShoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reviews' | '/shop' | '/shoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reviews' | '/shop' | '/shoes/$id'
  id: '__root__' | '/' | '/reviews' | '/shop' | '/shoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewsRoute: typeof ReviewsRoute
  ShopRoute: typeof ShopRoute
  ShoesIdRoute: typeof ShoesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes/$id': {
      id: '/shoes/$id'
      path: '/shoes/$id'
      fullPath: '/shoes/$id'
      preLoaderRoute: typeof ShoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewsRoute: ReviewsRoute,
  ShopRoute: ShopRoute,
  ShoesIdRoute: ShoesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
